version: '3'
services:
  mongodb:
    image: 'mongo:latest'
    container_name: 'mongodb'
    environment:
      - MONGO_INITDB_DATABASE=mongodb
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - ./mongodb:/data/db
    ports:
      - '27017:27017'
  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "3050:80"

  api:
    build:
      dockerfile: Dockerfile
      context: ./backend
    depends_on:
      - mongodb
    volumes:
      - /app/node_modules
      - ./backend:/app
    ports:
      - "7000:7000"
  client:
    stdin_open: true
    build:
      dockerfile: Dockerfile
      context: ./frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app
